export interface VizState {
  callStack: string[];
  rootSchedule: string[];
  microtaskQueue: string[];
  macrotaskQueue: string[];
  flagSync: boolean;
  laneSyncFill: number;
  laneTransitionFill: number;
  timelineProgress: number;
  highlightLines: number[];
  activeSection: "ensure" | "process" | "schedule" | null;
  comment: string;
  paintReady: boolean;
}

export interface Scenario {
  id: string;
  title: string;
  steps: VizState[];
  codeLines: string[];
}

const REAL_CODE = [

  `// ═══ ensureRootIsScheduled ═══════════════════════════════════`,
  `export function ensureRootIsScheduled(root: FiberRoot): void {`,
  `  // Эта функция вызывается каждый раз, когда root получает обновление.`,
  `  // Она делает ровно две вещи:`,
  `  // 1) гарантирует, что root находится в расписании (linked list),`,
  `  // 2) гарантирует, что существует микрозадача для обработки расписания.`,
  ``,
  `  // Добавляем root в расписание`,
  `  if (root === lastScheduledRoot || root.next !== null) {`,
  `    // Быстрый путь: этот root уже запланирован, ничего не делаем.`,
  `  } else {`,
  `    if (lastScheduledRoot === null) {`,
  `      firstScheduledRoot = lastScheduledRoot = root;`,
  `    } else {`,
  `      lastScheduledRoot.next = root;`,
  `      lastScheduledRoot = root;`,
  `    }`,
  `  }`,
  ``,
  `  // При каждом обновлении root ставим true, пока не обработаем.`,
  `  // Если false — можно быстро выйти из flushSync без проверки.`,
  `  mightHavePendingSyncWork = true;`,
  ``,
  `  // Планируем микрозадачу (если ещё не запланирована)`,
  `  ensureScheduleIsScheduled();`,
  `  // ^ внутри делает:`,
  `  // if (!didScheduleMicrotask) {`,
  `  //   didScheduleMicrotask = true;`,
  `  //   scheduleImmediateTask(processRootScheduleInMicrotask);`,
  `  // }`,
  ``,
  `  // DEV-only: пометка устаревших (legacy) обновлений для act()`,
  `  if (__DEV__ && !disableLegacyMode`,
  `      && ReactSharedInternals.isBatchingLegacy`,
  `      && root.tag === LegacyRoot) {`,
  `    ReactSharedInternals.didScheduleLegacyUpdate = true;`,
  `  }`,
  `}`,
  ``,

  `// ═══ processRootScheduleInMicrotask ════════════════════════`,
  `function processRootScheduleInMicrotask() {`,
  `  // Всегда вызывается внутри микрозадачи, НИКОГДА синхронно.`,
  `  didScheduleMicrotask = false;`,
  `  mightHavePendingSyncWork = false; // Пересчитаем ниже`,
  ``,
  `  // Проверяем: есть ли "нетерпеливые" (eager) transition?`,
  `  let syncTransitionLanes = NoLanes;`,
  `  if (currentEventTransitionLane !== NoLane) {`,
  `    if (shouldAttemptEagerTransition()) {`,
  `      syncTransitionLanes = currentEventTransitionLane;`,
  `    }`,
  `  }`,
  ``,
  `  const currentTime = now();`,
  `  let prev = null;`,
  `  let root = firstScheduledRoot; // Начало linked list`,
  `  while (root !== null) {`,
  `    const next = root.next;`,
  `    // ↓↓↓ Здесь принимается решение о планировании ↓↓↓`,
  `    const nextLanes = scheduleTaskForRootDuringMicrotask(`,
  `      root, currentTime`,
  `    );`,
  `    if (nextLanes === NoLane) {`,
  `      // Работы больше нет — удаляем root из расписания`,
  `      root.next = null;`,
  `      if (prev === null) firstScheduledRoot = next;`,
  `      else prev.next = next;`,
  `      if (next === null) lastScheduledRoot = prev;`,
  `    } else {`,
  `      prev = root;`,
  `      if (includesSyncLane(nextLanes) ||`,
  `          syncTransitionLanes !== NoLanes) {`,
  `        mightHavePendingSyncWork = true; // Есть sync работа!`,
  `      }`,
  `    }`,
  `    root = next; // Следующий root в linked list`,
  `  }`,
  ``,
  `  // Выполняем всю накопившуюся синхронную работу`,
  `  flushSyncWorkAcrossRoots_impl(syncTransitionLanes, false);`,
  `}`,
  ``,

  `// ═══ scheduleTaskForRootDuringMicrotask ════════════════════`,
  `function scheduleTaskForRootDuringMicrotask(`,
  `  root: FiberRoot, currentTime: number`,
  `): Lane {`,
  `  // Проверяем: не голодают ли какие-то lanes? Помечаем как expired`,
  `  markStarvedLanesAsExpired(root, currentTime);`,
  ``,
  `  // Определяем следующие lanes для обработки`,
  `  const nextLanes = getNextLanes(root, ...);`,
  `  const existingCallbackNode = root.callbackNode;`,
  ``,
  `  if (nextLanes === NoLanes) {`,
  `    // Работы нет — отменяем существующий callback`,
  `    if (existingCallbackNode !== null) cancelCallback(it);`,
  `    root.callbackNode = null;`,
  `    root.callbackPriority = NoLane;`,
  `    return NoLane;`,
  `  }`,
  ``,
  `  // ★ КЛЮЧЕВАЯ ТОЧКА ПРИНЯТИЯ РЕШЕНИЯ ★`,
  `  if (includesSyncLane(nextLanes)) {`,
  `    // SYNC → выполнится в конце микрозадачи, доп. задача не нужна`,
  `    root.callbackPriority = SyncLane;`,
  `    root.callbackNode = null;`,
  `    return SyncLane;  // → flushSyncWork() выше сделает рендер`,
  `  }`,
  ``,
  `  // НЕ SYNC → планируем через Scheduler (MessageChannel = макрозадача)`,
  `  let schedulerPriorityLevel;`,
  `  switch (lanesToEventPriority(nextLanes)) {`,
  `    case DiscreteEventPriority:    // Клик, ввод`,
  `    case ContinuousEventPriority:  // Скролл, drag`,
  `      schedulerPriorityLevel = UserBlockingPriority; break;`,
  `    case DefaultEventPriority:     // Transition, обычное обновление`,
  `      schedulerPriorityLevel = NormalPriority; break;`,
  `    case IdleEventPriority:        // Фоновая работа`,
  `      schedulerPriorityLevel = IdlePriority; break;`,
  `    default:`,
  `      schedulerPriorityLevel = NormalPriority; break;`,
  `  }`,
  ``,
  `  // ★ Задача уходит в MACROTASK очередь через MessageChannel ★`,
  `  const newCallbackNode = scheduleCallback(`,
  `    schedulerPriorityLevel,`,
  `    performWorkOnRootViaSchedulerTask.bind(null, root),`,
  `  );`,
  `  root.callbackPriority = newCallbackPriority;`,
  `  root.callbackNode = newCallbackNode;`,
  `  return newCallbackPriority;`,
  `}`,
];

const BASE: VizState = {
  callStack: [],
  rootSchedule: [],
  microtaskQueue: [],
  macrotaskQueue: [],
  flagSync: false,
  laneSyncFill: 0,
  laneTransitionFill: 0,
  timelineProgress: 0,
  highlightLines: [],
  activeSection: null,
  comment: "",
  paintReady: false,
};

function s(overrides: Partial<VizState>): VizState {
  return { ...BASE, ...overrides };
}

const syncSteps: VizState[] = [
  s({
    comment: "Пользователь нажимает кнопку. Событие onClick попадает в Call Stack.",
    callStack: ["onClick()"],
    timelineProgress: 5,
  }),
  s({
    comment: "Внутри обработчика вызывается setState(). React начинает планирование обновления.",
    callStack: ["onClick()", "setState()"],
    timelineProgress: 8,
  }),
  s({
    highlightLines: [1, 2, 3, 4, 5],
    activeSection: "ensure",
    comment: "setState() вызывает ensureRootIsScheduled(root). Эта функция делает ровно 2 вещи: добавляет root в расписание и гарантирует микрозадачу.",
    callStack: ["onClick()", "setState()", "ensureRootIsScheduled()"],
    timelineProgress: 10,
  }),
  s({
    highlightLines: [8, 9, 10, 11, 12],
    activeSection: "ensure",
    comment: "Проверка: root уже в расписании? Нет. lastScheduledRoot === null → root становится первым и последним в linked list.",
    callStack: ["onClick()", "setState()", "ensureRootIsScheduled()"],
    rootSchedule: ["Root #1"],
    timelineProgress: 14,
  }),
  s({
    highlightLines: [19, 20, 21],
    activeSection: "ensure",
    comment: "mightHavePendingSyncWork = true — флаг для flushSync. Говорит: «возможно, есть синхронная работа, не пропускай проверку».",
    callStack: ["onClick()", "setState()", "ensureRootIsScheduled()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    timelineProgress: 18,
  }),
  s({
    highlightLines: [23, 24, 25, 26, 27, 28, 29],
    activeSection: "ensure",
    comment: "ensureScheduleIsScheduled() — если ещё не запланирована микрозадача, планирует: scheduleImmediateTask(processRootScheduleInMicrotask). Задача летит в Microtask Queue.",
    callStack: ["onClick()", "setState()", "ensureRootIsScheduled()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    microtaskQueue: ["processRootScheduleInMicrotask"],
    timelineProgress: 22,
  }),
  s({
    highlightLines: [37],
    activeSection: "ensure",
    comment: "ensureRootIsScheduled() завершена. Это было БЫСТРО — никакого рендеринга тут нет, только бронирование места. Возвращаемся в onClick.",
    callStack: ["onClick()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    microtaskQueue: ["processRootScheduleInMicrotask"],
    timelineProgress: 26,
  }),
  s({
    comment: "Call Stack пуст. Движок JS проверяет Microtask Queue — видит задачу! Микрозадачи выполняются ДО следующего рендера браузера.",
    callStack: [],
    rootSchedule: ["Root #1"],
    flagSync: true,
    microtaskQueue: ["processRootScheduleInMicrotask"],
    timelineProgress: 30,
  }),
  s({
    highlightLines: [40, 41, 42, 43],
    activeSection: "process",
    comment: "Запускается processRootScheduleInMicrotask(). Сбрасывает флаги. Начинает обход linked list всех запланированных roots.",
    callStack: ["processRootScheduleInMicrotask()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    timelineProgress: 35,
  }),
  s({
    highlightLines: [55, 56, 57, 58, 59, 60, 61],
    activeSection: "process",
    comment: "Для каждого root вызывается scheduleTaskForRootDuringMicrotask(root, currentTime). Именно ТАМ решается, куда пойдёт работа.",
    callStack: ["processRootScheduleInMicrotask()", "scheduleTaskForRoot...()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    timelineProgress: 40,
  }),
  s({
    highlightLines: [86, 87, 89, 90],
    activeSection: "schedule",
    comment: "scheduleTaskForRootDuringMicrotask: сначала markStarvedLanesAsExpired (защита от голодания), потом getNextLanes — определяет какие lanes нужно обработать.",
    callStack: ["processRootScheduleInMicrotask()", "scheduleTaskForRoot...()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    laneSyncFill: 20,
    timelineProgress: 45,
  }),
  s({
    highlightLines: [101, 102, 103, 104, 105, 106, 107],
    activeSection: "schedule",
    comment: "★ КЛЮЧЕВОЙ МОМЕНТ: includesSyncLane(nextLanes) === TRUE! Обычный setState → lane = SyncLane. Возвращаем SyncLane — дополнительная задача НЕ нужна, всё выполнится в конце этой же микрозадачи.",
    callStack: ["processRootScheduleInMicrotask()", "scheduleTaskForRoot...()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    laneSyncFill: 50,
    timelineProgress: 52,
  }),
  s({
    highlightLines: [70, 71, 72, 73],
    activeSection: "process",
    comment: "Назад в processRootScheduleInMicrotask: nextLanes включает SyncLane → mightHavePendingSyncWork = true. Синхронная работа подтверждена.",
    callStack: ["processRootScheduleInMicrotask()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    laneSyncFill: 65,
    timelineProgress: 58,
  }),
  s({
    highlightLines: [78, 79],
    activeSection: "process",
    comment: "flushSyncWorkAcrossRoots_impl() — ВОТ ГДЕ РЕНДЕРИНГ. React рендерит компонент ПРЯМО СЕЙЧАС, синхронно, в микрозадаче. Main thread ЗАБЛОКИРОВАН.",
    callStack: ["processRootScheduleInMicrotask()", "flushSyncWork()", "renderRoot()", "commitRoot()"],
    rootSchedule: [],
    flagSync: true,
    laneSyncFill: 100,
    timelineProgress: 78,
  }),
  s({
    comment: "Рендеринг завершён. DOM обновлён. Только ТЕПЕРЬ браузер может нарисовать кадр. Весь пользовательский ввод ждал — UI заморожен.",
    callStack: [],
    rootSchedule: [],
    flagSync: false,
    laneSyncFill: 100,
    timelineProgress: 100,
    paintReady: true,
  }),
];

const transitionSteps: VizState[] = [
  s({
    comment: "Входящее сообщение через WebSocket. Обработчик onMessage попадает в Call Stack.",
    callStack: ["onMessage()"],
    timelineProgress: 5,
  }),
  s({
    comment: "startTransition(() => setState(...)). React помечает обновление специальной lane = TransitionLane (не SyncLane!).",
    callStack: ["onMessage()", "startTransition()", "setState()"],
    timelineProgress: 8,
  }),
  s({
    highlightLines: [1, 2, 3, 4, 5],
    activeSection: "ensure",
    comment: "Вызывается ensureRootIsScheduled(root) — тот же самый вход. Функция не знает про transition, она просто бронирует root.",
    callStack: ["onMessage()", "startTransition()", "setState()", "ensureRootIsScheduled()"],
    timelineProgress: 10,
  }),
  s({
    highlightLines: [8, 10, 11, 12],
    activeSection: "ensure",
    comment: "Root добавляется в linked list расписания. Пока — всё абсолютно одинаково с синхронным сценарием.",
    callStack: ["onMessage()", "startTransition()", "setState()", "ensureRootIsScheduled()"],
    rootSchedule: ["Root #1"],
    timelineProgress: 14,
  }),
  s({
    highlightLines: [21],
    activeSection: "ensure",
    comment: "mightHavePendingSyncWork = true. Флаг ставится ВСЕГДА — функция не проверяет какой lane у обновления.",
    callStack: ["onMessage()", "startTransition()", "setState()", "ensureRootIsScheduled()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    timelineProgress: 18,
  }),
  s({
    highlightLines: [23, 24, 25, 26, 27, 28, 29],
    activeSection: "ensure",
    comment: "Микрозадача запланирована. Пока — полная копия Sync пути. Разница наступит внутри processRootScheduleInMicrotask.",
    callStack: ["onMessage()", "startTransition()", "setState()", "ensureRootIsScheduled()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    microtaskQueue: ["processRootScheduleInMicrotask"],
    timelineProgress: 22,
  }),
  s({
    highlightLines: [37],
    activeSection: "ensure",
    comment: "ensureRootIsScheduled() завершена. Call Stack разматывается → onMessage заканчивается.",
    callStack: ["onMessage()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    microtaskQueue: ["processRootScheduleInMicrotask"],
    timelineProgress: 26,
  }),
  s({
    comment: "Call Stack пуст. Движок JS запускает микрозадачу из Microtask Queue.",
    callStack: [],
    rootSchedule: ["Root #1"],
    flagSync: true,
    microtaskQueue: ["processRootScheduleInMicrotask"],
    timelineProgress: 30,
  }),
  s({
    highlightLines: [40, 41, 42, 43],
    activeSection: "process",
    comment: "processRootScheduleInMicrotask() запускается. Сброс флагов, начало обхода roots.",
    callStack: ["processRootScheduleInMicrotask()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    timelineProgress: 35,
  }),
  s({
    highlightLines: [59, 60, 61],
    activeSection: "process",
    comment: "Вызываем scheduleTaskForRootDuringMicrotask(root). Именно тут всё разойдётся с Sync.",
    callStack: ["processRootScheduleInMicrotask()", "scheduleTaskForRoot...()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    timelineProgress: 40,
  }),
  s({
    highlightLines: [86, 87, 89, 90],
    activeSection: "schedule",
    comment: "markStarvedLanesAsExpired + getNextLanes. Определяем lanes: lane = TransitionLane (startTransition пометил!).",
    callStack: ["processRootScheduleInMicrotask()", "scheduleTaskForRoot...()"],
    rootSchedule: ["Root #1"],
    flagSync: true,
    laneTransitionFill: 20,
    timelineProgress: 45,
  }),
  s({
    highlightLines: [101, 102],
    activeSection: "schedule",
    comment: "★ КЛЮЧЕВОЙ МОМЕНТ: includesSyncLane(nextLanes) === FALSE! TransitionLane — это НЕ Sync. Пропускаем блок, идём дальше ↓",
    callStack: ["processRootScheduleInMicrotask()", "scheduleTaskForRoot...()"],
    rootSchedule: ["Root #1"],
    flagSync: false,
    laneTransitionFill: 35,
    timelineProgress: 50,
  }),
  s({
    highlightLines: [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121],
    activeSection: "schedule",
    comment: "Маппинг lane → приоритет Scheduler. TransitionLane → DefaultEventPriority → NormalSchedulerPriority.",
    callStack: ["processRootScheduleInMicrotask()", "scheduleTaskForRoot...()"],
    rootSchedule: ["Root #1"],
    flagSync: false,
    laneTransitionFill: 50,
    timelineProgress: 55,
  }),
  s({
    highlightLines: [123, 124, 125, 126, 127, 128, 129, 130],
    activeSection: "schedule",
    comment: "★ scheduleCallback(NormalPriority, performWork) — задача уходит в MACROTASK QUEUE через MessageChannel! Не в микрозадачу!",
    callStack: ["processRootScheduleInMicrotask()", "scheduleTaskForRoot...()"],
    rootSchedule: ["Root #1"],
    flagSync: false,
    laneTransitionFill: 60,
    macrotaskQueue: ["Scheduler: performWork"],
    timelineProgress: 60,
  }),
  s({
    highlightLines: [68, 69, 74, 75],
    activeSection: "process",
    comment: "Назад в processRootScheduleInMicrotask: nextLanes != Sync → mightHavePendingSyncWork остаётся false. Sync работы нет.",
    callStack: ["processRootScheduleInMicrotask()"],
    rootSchedule: ["Root #1"],
    flagSync: false,
    laneTransitionFill: 60,
    macrotaskQueue: ["Scheduler: performWork"],
    timelineProgress: 63,
  }),
  s({
    highlightLines: [78, 79],
    activeSection: "process",
    comment: "flushSyncWorkAcrossRoots_impl — но sync работы нет! Ничего не рендерится. Микрозадача завершена. Main thread СВОБОДЕН.",
    callStack: [],
    rootSchedule: ["Root #1"],
    flagSync: false,
    laneTransitionFill: 60,
    macrotaskQueue: ["Scheduler: performWork"],
    timelineProgress: 68,
    paintReady: true,
  }),
  s({
    comment: "Браузер рисует кадр! UI отзывчив — пользователь может печатать. А transition-рендеринг ещё ждёт в Macrotask Queue.",
    callStack: [],
    rootSchedule: ["Root #1"],
    flagSync: false,
    laneTransitionFill: 65,
    macrotaskQueue: ["Scheduler: performWork"],
    timelineProgress: 75,
    paintReady: true,
  }),
  s({
    comment: "В СЛЕДУЮЩЕМ цикле event loop: из Macrotask Queue берётся performWork. React начинает рендерить transition-обновление.",
    callStack: ["performWorkOnRoot()", "renderRootConcurrent()"],
    rootSchedule: [],
    flagSync: false,
    laneTransitionFill: 85,
    timelineProgress: 88,
  }),
  s({
    comment: "React рендерит. Если работа > 5мс — прерывается (time slicing), отдаёт управление браузеру, продолжает в следующем кадре.",
    callStack: ["performWorkOnRoot()", "renderRootConcurrent()", "workLoopConcurrent()"],
    rootSchedule: [],
    flagSync: false,
    laneTransitionFill: 95,
    timelineProgress: 94,
  }),
  s({
    comment: "Готово. Итог: пользователь НЕ ждал, UI был отзывчив всё время. Обновление произошло в фоне, порциями, без блокировки.",
    callStack: [],
    rootSchedule: [],
    flagSync: false,
    laneTransitionFill: 100,
    timelineProgress: 100,
    paintReady: true,
  }),
];

export const SCENARIOS: Scenario[] = [
  {
    id: "sync",
    title: "setState (Sync)",
    steps: syncSteps,
    codeLines: REAL_CODE,
  },
  {
    id: "transition",
    title: "startTransition",
    steps: transitionSteps,
    codeLines: REAL_CODE,
  },
];
